dist: xenial
language: python
python:
    - 3.8
    - 3.7

env:
    global:
        - POETRY_VIRTUALENVS_CREATE=false

cache:
    pip: true
    directories:
        - "$HOME/.cache/pypoetry"
        - "$HOME/.cache/pre-commit"

before_install: pip install pip -U
install: pip install poetry -U

before_script:
    - poetry update # Encountering RecursionError on install only
    - poetry install
    - poetry add tox-travis
script: tox

jobs:
    include:
        - stage: deploy
          name: Deploy to GitHub Pages
          if: branch = fuse OR tag IS present
          before_script: poetry add sphinx sphinx-rtd-theme toml
          script: make docs
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: $GITHUB_TOKEN
              local_dir: docs/_build
              keep_history: true
              on:
                  branch: fuse
