dynaconf_merge: true

default:
    database:
        password: password

development:
    dynaconf_merge: true
    database:
        password: dev_password


production:
    database__password: prod_password
