default:
    name: fuse-utils
    version: "1.0.0"
    authors:
        - "Shashanka Prajapati"
    python: 3.7
    dev: false
    PORT: 8080
    DB_NAME: mydb.db
    database:
        host: server.com
        user: default
    plugins:
        - core
    scripts:
        - install.sh
        - deploy.sh

development:
    dev: true
    database:
        user: dev_user
        dynaconf_merge: true
    plugins:
        - debug_toolbar
        - dynaconf_merge
    scripts:
        - dev.sh
        - test.sh
        - deploy.sh
        - dynaconf_merge_unique
#    DB_PATH: "@format {env[HOME]}/{this.current_env}/{this.DB_NAME}" # Change to jinja as currently format doesn't work with setenv

production:
    database:
        dynaconf_merge:
            user: prod_user
